modules:
  - module_type: llama_index_chunk
    chunk_method: [ Token, Sentence ]
    chunk_size: [ 1024, 512 ]
    chunk_overlap: 24
    add_file_name: ko
  - module_type: llama_index_chunk
    chunk_method: [ SentenceWindow ]
    window_size: 3
    add_file_name: ko
  - module_type: llama_index_chunk
    chunk_method: [ Semantic_llama_index ]
    embed_model: openai
    buffer_size: 1
    breakpoint_percentile_threshold: 95
    add_file_name: ko
  - module_type: langchain_chunk
    chunk_method: recursivecharacter
    separators: [ " ", "\n" ]
