modules:
  - module_type: langchain_parse
    parse_method: [ pdfminer, pdfplumber, pypdfium2, pypdf, pymupdf ]
  - module_type: langchain_parse
    parse_method: upstagedocumentparse
  - module_type: llamaparse
    result_type: markdown
    language: ko
  - module_type: table_hybrid_parse
    text_parse_module: langchain_parse
    text_params:
      parse_method: pdfplumber
    table_parse_module: langchain_parse
    table_params:
      parse_method: upstagedocumentparse
